### ISSUE TITLE
官网查到的和软件查到的不符

### ISSUE THREAD

**Issue by onhdrtyu** [fullalien/crazyE-android#2]
![screenshot_20180910-072221_samsung internet](https://user-images.githubusercontent.com/37494954/45270018-59ee8f00-b4ca-11e8-9807-8b91442121a2.jpg)
![screenshot_20180910-072209_crazye](https://user-images.githubusercontent.com/37494954/45270019-5e1aac80-b4ca-11e8-94a1-709ea40bb9f2.jpg)
如图。我该信哪一个？

**Comment by onhdrtyu** [comment]
是不是以官网中的「我的课程表」为准？

**Comment by Vinting** [comment]
肯定信官网

**Comment by onhdrtyu** [comment]
好的，感谢
